#!/bin/sh

# get project directory
prj_dir="$1"
if [ -z $prj_dir ]; then
	prj_dir=`pwd`
fi

# replace with absolute path
prj_dir=`readlink -f $prj_dir`

source_lst_file=$prj_dir/cscope.files

echo "Generating source file list..."
ag --path-to-ignore ~/.ignore -f --one-device -l --nocolor --nogroup --asm --cc --cpp --java '.' $prj_dir | sort > $source_lst_file.new

#filelist_changed=`cmp $source_lst_file $source_lst_file.new 2>&1`
mv $source_lst_file.new $source_lst_file

#echo "Updating gtag file..."
#if [ "$filelist_changed" ]; then
#	gtags -f $source_lst_file &
#else
#	global -u &
#fi

echo "Updating ctag file..."
ctags --C++-kinds=+p --fields=+iaS --extra=+q --langmap=java:+.aidl -L $source_lst_file &

echo "Updating cscope database..."
cscope -b -q -i $source_lst_file &

wait
echo "Done!"
