require("basic")
require("keybindings")
require('plugins')
require("colorscheme")
require("autocmds")
require("misc")

require("plugin-config.nvim-lspconfig")
require("plugin-config.nvim-treesitter")
require("plugin-config.nvim-cmp")
require("plugin-config.lualine")
require("plugin-config.hop")
require("plugin-config.telescope")
require("plugin-config.gitsigns")

require("plugin-config.netrw")
